### ISSUE TITLE
Program no longer works due to API changes: Update Needed

### ISSUE THREAD

**Issue by jadenquinn** [jordon31/OF-SCR#6]
This is the error I get: x
x

Enter the profile name to download (use TAB for automatic completion -- Or to see the full list):

elanorose
x

The content is being downloaded to the profiles/elanorose directory using OF-SCR.

Saving profile info...
Downloading avatar...
Downloading header...

An error has occurred: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Jaden\Downloads\OF-SCR-main\of-scr.py", line 591, in <module>
    media_downloaded, skipped_posts = download_posts(photo_posts, False, pbar, skip_tagged_posts=False, tag_folder="TaggedPosts") #Photo Post  -- True or False  -- (to decide if you want to skip posts with the tag "skip_tagged_posts)=")
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\Downloads\OF-SCR-main\of-scr.py", line 392, in download_posts
    was_downloaded = future.result()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\Downloads\OF-SCR-main\of-scr.py", line 293, in download_media
    ext = re.findall('\.\w+\?', source)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

Please try again.
x
x

Enter the profile name to download (use TAB for automatic completion -- Or to see the full list):

Traceback (most recent call last):
  File "C:\Users\Jaden\Downloads\OF-SCR-main\of-scr.py", line 470, in <module>
    SELECTED_MODELS = select_sub()
                      ^^^^^^^^^^^^
  File "C:\Users\Jaden\Downloads\OF-SCR-main\of-scr.py", line 212, in select_sub
    MODELS = prompt("\nEnter the profile name to download (use TAB for automatic completion -- Or to see the full list):\n\n", completer=username_completer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1420, in prompt
    return session.prompt(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1035, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\application\application.py", line 961, in run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\application\application.py", line 875, in run_async
    return await _run_async(f)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaden\AppData\Local\Programs\Python\Python311\Lib\site-packages\prompt_toolkit\application\application.py", line 740, in _run_async
    result = await f
             ^^^^^^^
KeyboardInterrupt
^C

**Comment by jordon31** [comment]
![image](https://github.com/jordon31/OF-SCR/assets/94505651/b7903a50-8b99-49b8-9728-45a690fb8953)


working for me

**Comment by jordon31** [comment]
as far as I understand you are on MAC.. i have a mac mini M1 too.. i have to try it if i have problems from there

**Comment by Alexo88** [comment]
I get the same problem from windows, it happens when I want to update the download to today's date.

`The folder profiles/edenetc exists.
Media already present will not be re-downloaded.
Saving profile info...

An error has occurred: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "D:\- GITHUB repo\OF-SCR-main\of-scr.py", line 594, in <module>
    media_downloaded, skipped_posts_2 = download_posts(video_posts, False, pbar, skip_tagged_posts=False, tag_folder="TaggedPosts") #Video Post -- True or False  -- (to decide if you want to skip posts with the tag "skip_tagged_posts)=")
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\- GITHUB repo\OF-SCR-main\of-scr.py", line 392, in download_posts
    was_downloaded = future.result()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\- GITHUB repo\OF-SCR-main\of-scr.py", line 293, in download_media
    ext = re.findall('\.\w+\?', source)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'`

**Comment by jordon31** [comment]
@Alexo88  

Thanks for your report. It will be fixed

**Comment by jordon31** [comment]
I'm updating.. sorry for the delay

**Comment by jordon31** [comment]
I fix all.. check new version

"https://github.com/jordon31/OF-SCR/blob/main/Change%20Version.md"

let me know if you have any problems

**Comment by jordon31** [comment]
anyway the problem appeared by you was a file duplication problem caused by "TaggedPosts" now I solved the problem.. removing that folder and automatically skipping posts with "@" "#ad" "#adv"

@jadenquinn it wasn't an API issue.

**Comment by jadenquinn** [comment]
> anyway the problem appeared by you was a file duplication problem caused by "TaggedPosts" now I solved the problem.. removing that folder and automatically skipping posts with "@" "#ad" "#adv"
> 
> @jadenquinn it wasn't an API issue.

It is, very much so. The problem I'm having is that the new "Blob" based Onlyfans videos on creator pages are not being downloaded correctly, as you can see here, these videos should be several minutes in length, but are only 2 seconds each, note that this is only for these "new" kinds of videos. They are interspersed with the rest of the videos on a given creator's page, but they cannot be downloaded at all the same way, making it impossible (for what I know and what I've been able to read) to download said videos from the page manually using inspect element or whatever like you could before, and apparently using scrapers as this as well are now useless for these videos.

Screenshot:
![clearly](https://github.com/jordon31/OF-SCR/assets/13245331/a1f49805-616d-4956-a7ca-cf4cac8d58b1)

**Comment by jordon31** [comment]
you have telegram?

> > anyway the problem appeared by you was a file duplication problem caused by "TaggedPosts" now I solved the problem.. removing that folder and automatically skipping posts with "@" "#ad" "#adv"
> > @jadenquinn it wasn't an API issue.
> 
> It is, very much so. The problem I'm having is that the new "Blob" based Onlyfans videos on creator pages are not being downloaded correctly, as you can see here, these videos should be several minutes in length, but are only 2 seconds each, note that this is only for these "new" kinds of videos. They are interspersed with the rest of the videos on a given creator's page, but they cannot be downloaded at all the same way, making it impossible (for what I know and what I've been able to read) to download said videos from the page manually using inspect element or whatever like you could before, and apparently using scrapers as this as well are now useless for these videos.
> 
> Screenshot: ![clearly](https://user-images.githubusercontent.com/13245331/256429951-a1f49805-616d-4956-a7ca-cf4cac8d58b1.PNG)

you have telegram?

**Comment by jadenquinn** [comment]
> > It is, very much so. The problem I'm having is that the new "Blob" based Onlyfans videos on creator pages are not being downloaded correctly, as you can see here, these videos should be several minutes in length, but are only 2 seconds each, note that this is only for these "new" kinds of videos. They are interspersed with the rest of the videos on a given creator's page, but they cannot be downloaded at all the same way, making it impossible (for what I know and what I've been able to read) to download said videos from the page manually using inspect element or whatever like you could before, and apparently using scrapers as this as well are now useless for these videos.
> 
> you have telegram?

Not really, I have Discord though.

**Comment by jordon31** [comment]
> Not really, I have Discord though. iRed#9321

Done

**Comment by jadenquinn** [comment]
This is still a problem, as the videos still download as 2 second videos, and these are videos that are actually upwards of 3 minutes on some of them.
